[package]
name = "things-gateway-rs"
version = "0.1.0"
authors = ["Claus Matzinger <claus.matzinger+kb@gmail.com>"]
edition = "2018"

[dependencies]
actix-web="0.7"
futures = "0.1"
env_logger = "0.6"
actix = "0.7"
rand = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"